// bdboard-sso1.12: dto.ts を src/interface/http/dto/*.ts へモジュール分割した際の、
// 型エクスポート面の回帰ガード。
//
// 値エクスポート (class/function/const) は dto.exportSurface.test.ts が
// `Object.keys()` で実行時に検証できるが、`export interface` / `export type` は
// TypeScript の型のみの宣言でコンパイルすると消える (実行時のバインディングを持たない)
// ため、Object.keys() には現れずその手法では検証できない。代わりに、分割前の main
// (コミット 5c92e2c、PR #533 マージ直後) の dto.ts から
// `grep -oE '^export (interface|type) [A-Za-z0-9_]+' src/interface/http/dto.ts` で
// 機械的に採取した型エクスポート名 (59件) を入口 (./dto.js) からまとめて import し、
// 1箇所の tuple 型で「使う」ことで `npm run build` (tsc --noEmit) に通す。
//
// 分割後の dto.ts は `export * from './dto/xxx'` の再エクスポート入口のみになった。
// ここが崩れる (型の移し忘れ・名前の変更・re-export の欠落) と、import 自体が解決
// できず tsc がこのファイルで落ちる (TS2305: has no exported member)。
import type {
  ActivityEventDto,
  AgeDistributionDto,
  AgentProcessDto,
  BoardCardDto,
  BoardDto,
  BoardViewDto,
  CfdDayEntryDto,
  CfdStatsDto,
  ChatAgentDto,
  CommentDto,
  DependencyEdgeDto,
  DependencyGraphDto,
  DiscoveredChatSessionDto,
  GraphEdgeDto,
  GraphNodeDto,
  HarnessKpiDto,
  HarnessShareKpiDto,
  HygieneCleanupTargetDto,
  HygieneCloseEvidenceStatusDto,
  HygieneCycleEdgeDto,
  HygieneHeartbeatLoopTargetDto,
  HygieneIssueDto,
  HygieneIssueKindDto,
  HygieneOverlapPeerDto,
  HygieneResponseDto,
  LeaseHealthDto,
  MergeSlotStatusDto,
  ModelStatsDto,
  ModelUsageDto,
  NonTicketHarnessWorktreeWarningDto,
  PendingDecisionDwellKpiDto,
  PrBadgeDto,
  ProjectBoardDto,
  ProjectCfdStatsDto,
  ProjectDto,
  ProjectThroughputStatsDto,
  ReclaimKpiDto,
  ReclaimProjectStatusDto,
  ReclaimSchedulerStatusDto,
  SessionDto,
  SessionHistoryEntryDto,
  SessionHistoryTicketDto,
  SessionTailMessageDto,
  StageModelCountsDto,
  StaleLeaseDto,
  ThroughputStatsDto,
  TicketChildDto,
  TicketDetailDto,
  TicketInFlightOverlapDto,
  TicketModelDto,
  TicketSearchResultDto,
  TicketSessionLinkDto,
  TicketSimilarResultDto,
  TicketSummaryDto,
  TicketTokenUsageDto,
  ToBoardDtoOptions,
  ToProjectDtoOptions,
  WeeklyCloseCountDto,
  WeeklyModelCloseCountsDto,
} from './dto.js';

// 全型を1箇所で「使う」ための tuple。コンパイル後は消える (実行時に影響しない)。
export type DtoTypeExportSurfaceCheck = [
  ActivityEventDto,
  AgeDistributionDto,
  AgentProcessDto,
  BoardCardDto,
  BoardDto,
  BoardViewDto,
  CfdDayEntryDto,
  CfdStatsDto,
  ChatAgentDto,
  CommentDto,
  DependencyEdgeDto,
  DependencyGraphDto,
  DiscoveredChatSessionDto,
  GraphEdgeDto,
  GraphNodeDto,
  HarnessKpiDto,
  HarnessShareKpiDto,
  HygieneCleanupTargetDto,
  HygieneCloseEvidenceStatusDto,
  HygieneCycleEdgeDto,
  HygieneHeartbeatLoopTargetDto,
  HygieneIssueDto,
  HygieneIssueKindDto,
  HygieneOverlapPeerDto,
  HygieneResponseDto,
  LeaseHealthDto,
  MergeSlotStatusDto,
  ModelStatsDto,
  ModelUsageDto,
  NonTicketHarnessWorktreeWarningDto,
  PendingDecisionDwellKpiDto,
  PrBadgeDto,
  ProjectBoardDto,
  ProjectCfdStatsDto,
  ProjectDto,
  ProjectThroughputStatsDto,
  ReclaimKpiDto,
  ReclaimProjectStatusDto,
  ReclaimSchedulerStatusDto,
  SessionDto,
  SessionHistoryEntryDto,
  SessionHistoryTicketDto,
  SessionTailMessageDto,
  StageModelCountsDto,
  StaleLeaseDto,
  ThroughputStatsDto,
  TicketChildDto,
  TicketDetailDto,
  TicketInFlightOverlapDto,
  TicketModelDto,
  TicketSearchResultDto,
  TicketSessionLinkDto,
  TicketSimilarResultDto,
  TicketSummaryDto,
  TicketTokenUsageDto,
  ToBoardDtoOptions,
  ToProjectDtoOptions,
  WeeklyCloseCountDto,
  WeeklyModelCloseCountsDto,
];
